variable eks_name{}
variable private_subnets{}
variable eks_role_arn{}
variable eksnode_role_arn{}
variable eksnode_name{}
variable instance_types{}
variable minnode{}
variable maxnode{}
variable desirednode{}
variable keyname{}
variable clusterautoscalerrole{}
variable clusterautoscalerpolicy{}