variable "vpc_name"{}
variable "vpc_cidr"{}
variable "ig_name"{}
variable "publicsubnet_name"{}
variable "public_subnets"{}
variable "private_subnets"{}
variable "availability_zones"{}
variable "nat_name"{}
variable "routetable_name"{}
variable "workspace"{}